
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/navbars/navbar";
import { Providers } from "./lib/providers/provider";
import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
const session = await getServerSession();

  return (
    <html lang="en">
      <body className={inter.className}>
      <Providers session={session}>

          {/* <Toaster position="top-right" expand={true} richColors /> */}
          {children}
        </Providers>
        </body>
    </html>
  );
}
